using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class GameUI : MonoBehaviour
{
    public static GameUI instance;


    [SerializeField]private GameObject deathPanel;
    void Awake(){
        instance =this;
    }
    


    public static void ShowDeath(){
        instance.showDeath();
    }

    void showDeath(){
        deathPanel.SetActive(true);
    }



    public void Restart(){
        SceneManager.LoadScene(2);
    }

    public void Menu(){
        SceneManager.LoadScene(0);
    }
}
